const taskStartBlockWebsite: {[name: string]: string } = {
    welcome_task_1: '<xml xmlns="https://developers.google.com/blockly/xml"> <block type="text" id="S1bfFYTuoa@1b+w*WCQG" x="265" y="95"> <field name="TEXT">Hello World</field> </block> <block type="procedures_defreturn" id="q/PSk~LBXun$I?S4O_To" x="181" y="141"> <field name="NAME">SayHi</field> <comment pinned="false" h="80" w="160">Describe this function...</comment> </block> </xml>',
    welcome_task_2: '<xml xmlns="https://developers.google.com/blockly/xml"> <block type="procedures_defreturn" id="q/PSk~LBXun$I?S4O_To" x="181" y="141"> <field name="NAME">SayCode</field> <comment pinned="false" h="80" w="160">Describe this function...</comment> <value name="RETURN"> <block type="text" id="S1bfFYTuoa@1b+w*WCQG"> <field name="TEXT">Hello World</field> </block> </value> </block> </xml>',
    math_task_1: '<xml xmlns="https://developers.google.com/blockly/xml"> <block type="math_number" id="Ok#]ztlugyOhVDYhMxq(" x="194" y="62"> <field name="NUM">123</field> </block> <block type="math_arithmetic" id=":Nccv0MS`;,b[6#H2Mjd" x="266" y="83"> <field name="OP">ADD</field> <value name="A"> <shadow type="math_number" id="=lmXh|[Mwk}mM)r(Chfp"> <field name="NUM">1</field> </shadow> </value> <value name="B"> <shadow type="math_number" id="v-c^~j6%?)+!vMCH+aON"> <field name="NUM">1</field> </shadow> </value> </block> <block type="math_number" id="?dTaDq.iWL_%d(4BlfM^" x="194" y="100"> <field name="NUM">123</field> </block> <block type="procedures_defreturn" id="q/PSk~LBXun$I?S4O_To" x="181" y="141"> <field name="NAME">SolveMathProblem</field> <comment pinned="false" h="80" w="160">Describe this function...</comment> </block> </xml>',
    math_task_2: '<xml xmlns="https://developers.google.com/blockly/xml"> <variables> <variable id="?6H;(583zUsIgkj9Hbjb">x</variable> <variable id="X0NLpB.fSzc?w1yno/r3">y</variable> </variables> <block type="variables_get" id="GH5jg4cG:`RM?f3%R#IK" x="189" y="58"> <field name="VAR" id="X0NLpB.fSzc?w1yno/r3">y</field> </block> <block type="math_arithmetic" id=":Nccv0MS`;,b[6#H2Mjd" x="266" y="83"> <field name="OP">ADD</field> <value name="A"> <shadow type="math_number" id="=lmXh|[Mwk}mM)r(Chfp"> <field name="NUM">1</field> </shadow> </value> <value name="B"> <shadow type="math_number" id="v-c^~j6%?)+!vMCH+aON"> <field name="NUM">1</field> </shadow> </value> </block> <block type="variables_get" id="P$+e@~`deMlDW4UB)Idu" x="190" y="96"> <field name="VAR" id="?6H;(583zUsIgkj9Hbjb">x</field> </block> <block type="procedures_defreturn" id="q/PSk~LBXun$I?S4O_To" x="181" y="141"> <mutation> <arg name="x" varid="?6H;(583zUsIgkj9Hbjb"></arg> <arg name="y" varid="X0NLpB.fSzc?w1yno/r3"></arg> </mutation> <field name="NAME">SolveMathProblem</field> <comment pinned="false" h="80" w="160">Describe this function...</comment> </block> </xml>',
    math_task_3: '<xml xmlns="https://developers.google.com/blockly/xml"> <variables> <variable id="?6H;(583zUsIgkj9Hbjb">x</variable> <variable id="X0NLpB.fSzc?w1yno/r3">y</variable> </variables> <block type="procedures_defreturn" id="q/PSk~LBXun$I?S4O_To" x="181" y="141"> <mutation> <arg name="x" varid="?6H;(583zUsIgkj9Hbjb"></arg> <arg name="y" varid="X0NLpB.fSzc?w1yno/r3"></arg> </mutation> <field name="NAME">SolveMathProblem</field> <comment pinned="false" h="80" w="160">Describe this function...</comment> </block> </xml>',
    test_task: '<xml xmlns="https://developers.google.com/blockly/xml"> <block type="procedures_defreturn" id="9sb{:3@O1]f:}%:~4iZ*" x="106" y="161"> <field name="NAME">test</field> <comment pinned="false" h="80" w="160">Describe this function...</comment> </block> <block type="logic_boolean" id="|lZe:x;@#W#PgA7}5M0~" x="275" y="166"> <field name="BOOL">TRUE</field> </block> </xml>',
    drive_task: '<xml xmlns="https://developers.google.com/blockly/xml"> <variables> <variable id="r9jRe{S@h-NUz#MiYC5v">age</variable> <variable id="P+-5TS^xBD/A6qX{8s`W">isDrunk</variable> </variables> <block type="variables_get" id=")yXh}{)$c7t;~*EeLHh6" x="104" y="123"> <field name="VAR" id="r9jRe{S@h-NUz#MiYC5v">age</field> </block> <block type="variables_get" id="O54R=6gvK(tCbhu{HGyI" x="181" y="124"> <field name="VAR" id="P+-5TS^xBD/A6qX{8s`W">isDrunk</field> </block> <block type="procedures_defreturn" id="9sb{:3@O1]f:}%:~4iZ*" x="106" y="161"> <mutation> <arg name="age" varid="r9jRe{S@h-NUz#MiYC5v"></arg> <arg name="isDrunk" varid="P+-5TS^xBD/A6qX{8s`W"></arg> </mutation> <field name="NAME">canDrive</field> <comment pinned="false" h="80" w="160">Checks if a person can drive or not</comment> </block> </xml>',
    sum_task: '<xml xmlns="https://developers.google.com/blockly/xml"> <variables> <variable id="{)?kE5?B4^PZTYM~fj$R">x</variable> <variable id="(+5Gf4TVd_=526g!y.a#">y</variable> </variables> <block type="variables_get" id="#}w_Mk^%b(=7A|b@?aH:" x="172" y="66"> <field name="VAR" id="{)?kE5?B4^PZTYM~fj$R">x</field> </block> <block type="variables_get" id="(dw*iot[^NE$yhXhjD9f" x="227" y="66"> <field name="VAR" id="(+5Gf4TVd_=526g!y.a#">y</field> </block> <block type="procedures_defreturn" id="?P:fX^^Nm!G{yngThf$4" x="178" y="102"> <mutation> <arg name="x" varid="{)?kE5?B4^PZTYM~fj$R"></arg> <arg name="y" varid="(+5Gf4TVd_=526g!y.a#"></arg> </mutation> <field name="NAME">addTwoNumbers</field> <comment pinned="false" h="80" w="160">Returns the sum of two numbers</comment> </block> </xml>'
}

export default taskStartBlockWebsite;